source = ./bindings.conf

# DISABLE laptop keybord
#device[at-translated-set-2-keyboard]:enabled = false

# setup polish keybord
input {
  kb_layout = pl
  kb_options = lv3:ralt_switch
  # follow_mouse = 0
}


# workspace
workspace = 1, monitor:eDP-1


windowrule = match:class .*(keepassxc|bitrix24|Spotify|chrome-mail.google.com).*, workspace 1
windowrule = match:class .*(code).*, workspace 2
windowrule = match:class .*bitrix24.*, group new

# setting a waybar date
# /home/grzegorz/.config/waybar/config.jsonc
# "clock": {
#     "format": "{:L%m.%d %A %H:%M}",
