# See https://wiki.hyprland.org/Configuring/Monitors/

# BIURO

monitor=DP-3,3840x2160@60,0x0,1.5
monitor=DP-1,3840x2160@60,2560x0,1.5
monitor=eDP-1,1920x1200@60,5120x600,1.25

# 3840/1.5*2

workspace=2,monitor:DP-1
workspace=2,monitor:DP-2
workspace=3,monitor:DP-1
workspace=3,monitor:DP-2
